services:
  db:
    image: mongo
    container_name: myAPIdb
    restart: always
    ports:
      - 27017:27017
    env_file:
      - .env
    volumes:
      - type: volume
        source: my_api_db_data
        target: /data/db

  api:
    image: fastapi-todos
    platform: linux/amd64
    container_name: fastapi-todos
    restart: always
    ports:
      - 8002:8000
    env_file:
      - .env
    depends_on:
      - db
  # server:
  #   image: nginx:1.25-alpine
  #   container_name: nginx
  #   restart: always
  #   ports:
  #     - 443:443
  #   volumes:
  #     - type: bind
  #       read_only: true
  #       source: ./nginx/nginx.conf  # Update this path to your actual nginx.conf file
  #       target: /etc/nginx/nginx.conf
  #     - type: bind
  #       read_only: true
  #       source: /etc/ssl/certs
  #       target: /etc/ssl/certs
  #   depends_on:
  #     - api

volumes:
  my_api_db_data:

