services:
  db:
    image: mongo
    container_name: myAPIdb
    restart: always
    ports:
      - 27017:27017
    env_file:
      - .env
    volumes:
      - type: volume
        source: my_api_db_data
        target: /data/db

  api:
    image: fastapi-todos
    platform: linux/amd64 
    container_name: fastapi-todos
    restart: always
    ports:
      - 8002:8000
    env_file:
      - .env
    depends_on:
      - db

volumes:
  my_api_db_data:
